# Generated by Django 4.2.1 on 2023-06-07 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projet_groupe_c', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('modification_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_user_id', models.IntegerField()),
                ('shared_with_user_id', models.IntegerField()),
                ('share_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shared_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_groupe_c.shareditem')),
            ],
        ),
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projet_groupe_c.item')),
                ('shared_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_groupe_c.shareditem')),
            ],
        ),
        migrations.CreateModel(
            name='Archived',
            fields=[
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projet_groupe_c.item')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_groupe_c.itemhistory')),
            ],
        ),
    ]
