# Generated by Django 4.2.1 on 2023-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_groupe_c', '0003_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='password_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
